apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parts-backend
  template:
    metadata:
      labels:
        app: parts-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/bcbeco/parts-backend:latest
        ports:
        - containerPort: 8080