apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parts-ingress
spec:
  rules:
  - host: parts.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: parts-frontend-service
            port:
              number: 80